# Generated by Django 5.1.7 on 2025-04-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent',
            field=models.PositiveIntegerField(),
        ),
    ]
