# Generated by Django 5.1.7 on 2025-03-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Houses",
            new_name="House",
        ),
    ]
