# Generated by Django 5.1.7 on 2025-04-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0002_alter_house_bedrooms_alter_house_beds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='specialist_user',
        ),
    ]
