# Generated by Django 5.1.7 on 2025-04-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0003_remove_specialist_specialist_user'),
    ]
    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE Accommodation_student 
            ADD COLUMN student_user_id integer REFERENCES auth_user(id) ON DELETE CASCADE;
            """,
            """
            ALTER TABLE Accommodation_student DROP COLUMN student_user_id;
            """
        ),
    ]