# Generated by Django 5.1.7 on 2025-04-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0003_remove_specialist_specialist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_user',
        ),
    ]
