# Generated by Django 5.1.7 on 2025-04-08 14:49

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0004_fix_student_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, default=''),
            preserve_default=False,
        ),
    ]
