# Generated by Django 5.1.7 on 2025-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Accommodation",
            "0006_remove_house_location_remove_reservation_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="house",
            new_name="house_id",
        ),
    ]
