# Generated by Django 5.1.7 on 2025-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0007_rename_house_reservation_house_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="period_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="period_to",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                max_length=100,
            ),
        ),
    ]
