# Generated by Django 5.1.7 on 2025-04-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0008_alter_reservation_period_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="rating",
        ),
        migrations.AddField(
            model_name="house",
            name="FoD",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="house",
            name="KC",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="house",
            name="MC",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="house",
            name="SIMS",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="house",
            name="SRC",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="house",
            name="available_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="available_to",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("comment", models.TextField()),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accommodation.house",
                    ),
                ),
            ],
        ),
    ]
