# Generated by Django 5.1.7 on 2025-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Accommodation",
            "0009_remove_house_rating_house_fod_house_kc_house_mc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="create_date",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=100,
            ),
        ),
    ]
