# Generated by Django 5.1.7 on 2025-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0010_reservation_create_date_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_date",
            field=models.DateTimeField(default="1970-01-01"),
        ),
    ]
