# Generated by Django 5.1.7 on 2025-04-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0005_fix_student_fields_2'),
        ('Accommodation', '0011_alter_reservation_create_date'),
    ]

    operations = [
    ]
