# Generated by Django 5.1.7 on 2025-04-14 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0012_merge_20250414_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(default=3035999999, on_delete=django.db.models.deletion.CASCADE, to='Accommodation.student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('created', 'New Reservation'), ('cancelled', 'Cancel Reservation')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accommodation.reservation')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Accommodation.specialist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
