# Generated by Django 5.1.7 on 2025-04-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0013_rating_created_at_rating_student_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
