# Generated by Django 5.2 on 2025-04-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accommodation", "0013_delete_notification"),
        (
            "Accommodation",
            "0018_alter_house_flat_number_alter_house_floor_number_and_more",
        ),
    ]

    operations = []
